spring:
  profiles:
    active: demo
  cloud:
    stream:
      default:
        content-type: application/json
  datasource:
    url: 'jdbc:postgresql://localhost:5432/${db.name}?stringtype=unspecified'
    username: '${db.user}'
    password: '${db.password}'
  jpa:
    properties:
      hibernate: #Все проперти для jpa и hibernate задаются здесь
        hbm2ddl:
          auto: none #disable for prod
  liquibase:
    change-log: classpath:liquebase/changelog.xml
    enabled: true

#logging.level.org.hibernate: DEBUG
#logging.level.org.hibernate.type: TRACE

veeva:
  objects:
    tables:
      study__v: veeva_study
      country__v: veeva_country
      study_country__v: veeva_study_country
      milestone__v: veeva_milestone
      milestone_item__v: veeva_milestone_item
      visit__v: veeva_visit
      visit_def__v: veeva_visit_definition
      hierarchy__v: veeva_artifact
      model__v: veeva_model
      site__v: veeva_site
      team_role__v: veeva_team_role
      study_organization__v: veeva_study_organization
      organization_role__v: veeva_organization_role
      monitored_subject_visit__v: veeva_monitored_subject_visit
      organization__v: veeva_organization
      monitored_open_follow_up_items__v: veeva_monitored_open_item
      monitored_closed_follow_up_items__v: veeva_monitored_closed_item
      contact_information__clin: veeva_contact_information
      subject__clin: veeva_subject
      study_person__clin: veeva_study_person
      monitored_subject__ctms: veeva_monitored_subject
      monitored_subject_event__ctms: veeva_monitored_subject_event
      monitored_metrics__ctms: veeva_monitored_metrics
      monitoring_visit_participant__ctms: veeva_monitoring_visit_participant
      monitoring_event__ctms: veeva_monitoring_event
      monitoring_activity__ctms: veeva_monitoring_activity
      trip_report_answer__ctms: veeva_trip_report_answer
      trip_report_question_response__ctms: veeva_trip_report_question_response
      trip_report_question_template__ctms: veeva_trip_report_question_template
      person__sys: veeva_person
      clinical_user_task__clin: veeva_clinical_user_task
      issues1__c: veeva_issue
      issues__c: veeva_issue
