spring:
  profiles:
    active: demo
  cloud:
    stream:
      default:
        content-type: application/json
  datasource:
    url: 'jdbc:postgresql://localhost:5432/${db.name}?stringtype=unspecified'
    username: '${db.user}'
    password: '${db.password}'
  jpa:
    properties:
      hibernate: #Все проперти для jpa и hibernate задаются здесь
        hbm2ddl:
          auto: none #disable for prod
  liquibase:
    change-log: classpath:liquebase/changelog.xml
    enabled: true

#logging.level.org.hibernate: DEBUG
#logging.level.org.hibernate.type: TRACE